"""initial

Revision ID: 6b0980f52d48
Revises: 
Create Date: 2026-05-26 13:16:04.873138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b0980f52d48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    op.create_table('countries',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=56), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_created_at'), 'countries', ['created_at'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_countries_updated_at'), 'countries', ['updated_at'], unique=False)
    op.create_table('feed_categories',
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_categories_created_at'), 'feed_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_categories_name'), 'feed_categories', ['name'], unique=True)
    op.create_index(op.f('ix_feed_categories_updated_at'), 'feed_categories', ['updated_at'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_created_at'), 'skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_skills_updated_at'), 'skills', ['updated_at'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_tags_updated_at'), 'tags', ['updated_at'], unique=False)
    op.create_table('cities',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=168), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'name', name='uq_city_name_country_id')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_created_at'), 'cities', ['created_at'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_updated_at'), 'cities', ['updated_at'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tagline', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('startup', 'product_company', 'agency', 'outsourcing', 'outstaffing', 'enterprise', 'government', name='company_type'), nullable=False),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'suspended', name='company_status'), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_city_id'), 'companies', ['city_id'], unique=False)
    op.create_index(op.f('ix_companies_country_id'), 'companies', ['country_id'], unique=False)
    op.create_index(op.f('ix_companies_created_at'), 'companies', ['created_at'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_updated_at'), 'companies', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('headline', sa.String(length=120), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Enum('frontend', 'backend', 'fullstack', 'ios', 'android', 'cross_platform_mobile', 'desktop', 'embedded', 'systems', 'firmware', 'devops', 'platform', 'sre', 'cloud', 'data_engineering', 'data_science', 'machine_learning', 'ai_engineering', 'data_analytics', 'security', 'application_security', 'blockchain', 'game', 'qa', 'ui_ux', 'developer_relations', 'technical_writing', name='specialization'), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('telegram_username', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'pending_verification', 'deleted', name='user_status'), nullable=False),
    sa.Column('follow_policy', sa.Enum('auto_accept', 'require_approval', name='follow_policy'), nullable=False),
    sa.Column('job_search_status', sa.Enum('actively_looking', 'open_to_offers', 'interviewing', 'not_looking', name='job_search_status'), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.create_index(op.f('ix_users_country_id'), 'users', ['country_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('activities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('last_activity_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_date')
    )
    op.create_index(op.f('ix_activities_activity_date'), 'activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_updated_at'), 'activities', ['updated_at'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('attachments',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', name='attachment_status'), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_created_at'), 'attachments', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attachments_status'), 'attachments', ['status'], unique=False)
    op.create_index(op.f('ix_attachments_updated_at'), 'attachments', ['updated_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('reply_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_reply_id'), 'chat_messages', ['reply_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_updated_at'), 'chat_messages', ['updated_at'], unique=False)
    op.create_table('chat_participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('background_url', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_online_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_chat_participant')
    )
    op.create_index(op.f('ix_chat_participants_chat_id'), 'chat_participants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_created_at'), 'chat_participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_participants_last_seen_at'), 'chat_participants', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_chat_participants_updated_at'), 'chat_participants', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False)
    op.create_table('company_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'recruiter', 'owner', name='company_member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_company_member')
    )
    op.create_index(op.f('ix_company_members_created_at'), 'company_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_members_updated_at'), 'company_members', ['updated_at'], unique=False)
    op.create_table('feeds',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('feed_visibility', sa.Enum('public', 'followers', 'private', name='feed_visibility'), nullable=False),
    sa.Column('comment_policy', sa.Enum('everyone', 'followers', 'nobody', name='comment_policy'), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['feed_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['feeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_author_id'), 'feeds', ['author_id'], unique=False)
    op.create_index(op.f('ix_feeds_category_id'), 'feeds', ['category_id'], unique=False)
    op.create_index(op.f('ix_feeds_created_at'), 'feeds', ['created_at'], unique=False)
    op.create_index(op.f('ix_feeds_parent_id'), 'feeds', ['parent_id'], unique=False)
    op.create_index(op.f('ix_feeds_quote_id'), 'feeds', ['quote_id'], unique=False)
    op.create_index(op.f('ix_feeds_updated_at'), 'feeds', ['updated_at'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='follow_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follower_following')
    )
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index(op.f('ix_follows_updated_at'), 'follows', ['updated_at'], unique=False)
    op.create_table('groups',
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('background_url', sa.Text(), nullable=True),
    sa.Column('group_type', sa.Enum('public', 'private', name='group_type'), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_group_name')
    )
    op.create_index(op.f('ix_groups_created_at'), 'groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_groups_updated_at'), 'groups', ['updated_at'], unique=False)
    op.create_table('oauth_users',
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'github', name='provider'), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_user_provider')
    )
    op.create_index(op.f('ix_oauth_users_created_at'), 'oauth_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_users_updated_at'), 'oauth_users', ['updated_at'], unique=False)
    op.create_table('posts',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='post_status'), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_updated_at'), 'posts', ['updated_at'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('specialization', sa.Enum('frontend', 'backend', 'fullstack', 'ios', 'android', 'cross_platform_mobile', 'desktop', 'embedded', 'systems', 'firmware', 'devops', 'platform', 'sre', 'cloud', 'data_engineering', 'data_science', 'machine_learning', 'ai_engineering', 'data_analytics', 'security', 'application_security', 'blockchain', 'game', 'qa', 'ui_ux', 'developer_relations', 'technical_writing', name='specialization'), nullable=False),
    sa.Column('salary_expectation_min', sa.Integer(), nullable=True),
    sa.Column('salary_expectation_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.Enum('UZS', 'KZT', 'KGS', 'TJS', 'TMT', 'USD', 'EUR', 'TRY', name='salary_currency'), nullable=True),
    sa.Column('work_format', sa.Enum('onsite', 'remote', 'hybrid', name='work_format'), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', name='employment_type'), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('salary_expectation_min <= salary_expectation_max', name='chk_resume_salary_expectation_range'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_city_id'), 'resumes', ['city_id'], unique=False)
    op.create_index(op.f('ix_resumes_country_id'), 'resumes', ['country_id'], unique=False)
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resumes_employment_type'), 'resumes', ['employment_type'], unique=False)
    op.create_index(op.f('ix_resumes_salary_expectation_max'), 'resumes', ['salary_expectation_max'], unique=False)
    op.create_index(op.f('ix_resumes_salary_expectation_min'), 'resumes', ['salary_expectation_min'], unique=False)
    op.create_index(op.f('ix_resumes_specialization'), 'resumes', ['specialization'], unique=False)
    op.create_index(op.f('ix_resumes_updated_at'), 'resumes', ['updated_at'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_addr', sa.String(length=45), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sessions_updated_at'), 'sessions', ['updated_at'], unique=False)
    op.create_table('user_skill_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('last_used_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill')
    )
    op.create_index(op.f('ix_user_skill_links_created_at'), 'user_skill_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_skill_links_updated_at'), 'user_skill_links', ['updated_at'], unique=False)
    op.create_table('vacancies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('external_apply_url', sa.Text(), nullable=True),
    sa.Column('submission_type', sa.Enum('profile', 'resume', name='submission_type'), nullable=False),
    sa.Column('specialization', sa.Enum('frontend', 'backend', 'fullstack', 'ios', 'android', 'cross_platform_mobile', 'desktop', 'embedded', 'systems', 'firmware', 'devops', 'platform', 'sre', 'cloud', 'data_engineering', 'data_science', 'machine_learning', 'ai_engineering', 'data_analytics', 'security', 'application_security', 'blockchain', 'game', 'qa', 'ui_ux', 'developer_relations', 'technical_writing', name='specialization'), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.Enum('UZS', 'KZT', 'KGS', 'TJS', 'TMT', 'USD', 'EUR', 'TRY', name='salary_currency'), nullable=True),
    sa.Column('payment_frequency', sa.Enum('hourly', 'daily', 'once_a_week', 'twice_a_month', 'once_a_month', 'per_project', name='payment_frequency'), nullable=True),
    sa.Column('years_of_experience_min', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('work_format', sa.Enum('onsite', 'remote', 'hybrid', name='work_format'), nullable=False),
    sa.Column('work_hours_per_week', sa.SmallInteger(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'internship', name='employment_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'archived', 'closed', name='vacancy_status'), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('salary_min <= salary_max', name='chk_vacancy_salary_range'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_city_id'), 'vacancies', ['city_id'], unique=False)
    op.create_index(op.f('ix_vacancies_country_id'), 'vacancies', ['country_id'], unique=False)
    op.create_index(op.f('ix_vacancies_created_at'), 'vacancies', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancies_specialization'), 'vacancies', ['specialization'], unique=False)
    op.create_index(op.f('ix_vacancies_title'), 'vacancies', ['title'], unique=False)
    op.create_index(op.f('ix_vacancies_updated_at'), 'vacancies', ['updated_at'], unique=False)
    op.create_table('work_experiences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR started_at <= ended_at', name='chk_work_experience_date_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experiences_created_at'), 'work_experiences', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_experiences_updated_at'), 'work_experiences', ['updated_at'], unique=False)
    op.create_table('applications',
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'viewed', 'shortlisted', 'interview', 'offer', 'rejected', 'hired', name='application_status'), nullable=False),
    sa.Column('recruiter_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', 'vacancy_id', name='uq_application')
    )
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_updated_at'), 'applications', ['updated_at'], unique=False)
    op.create_table('chat_message_attachment_links',
    sa.Column('chat_message_id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_message_id', 'attachment_id', name='uq_chat_message_attachment'),
    sa.UniqueConstraint('chat_message_id', 'position', name='uq_chat_message_attachment_position')
    )
    op.create_index(op.f('ix_chat_message_attachment_links_attachment_id'), 'chat_message_attachment_links', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_chat_message_attachment_links_chat_message_id'), 'chat_message_attachment_links', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_chat_message_attachment_links_created_at'), 'chat_message_attachment_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_message_attachment_links_updated_at'), 'chat_message_attachment_links', ['updated_at'], unique=False)
    op.create_table('feed_attachment_links',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'attachment_id', name='uq_feed_attachment'),
    sa.UniqueConstraint('feed_id', 'position', name='uq_feed_attachment_position')
    )
    op.create_index(op.f('ix_feed_attachment_links_attachment_id'), 'feed_attachment_links', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_feed_attachment_links_created_at'), 'feed_attachment_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_attachment_links_feed_id'), 'feed_attachment_links', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_attachment_links_updated_at'), 'feed_attachment_links', ['updated_at'], unique=False)
    op.create_table('feed_engagements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('quote', 'repost', 'like', 'view', 'bookmark', name='feed_engagement_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feed_id', 'type', name='uq_user_feed_engagement')
    )
    op.create_index(op.f('ix_feed_engagements_created_at'), 'feed_engagements', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_engagements_feed_id'), 'feed_engagements', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_engagements_updated_at'), 'feed_engagements', ['updated_at'], unique=False)
    op.create_index(op.f('ix_feed_engagements_user_id'), 'feed_engagements', ['user_id'], unique=False)
    op.create_table('feed_tag_links',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'tag_id', name='uq_feed_tag')
    )
    op.create_index(op.f('ix_feed_tag_links_created_at'), 'feed_tag_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_feed_tag_links_feed_id'), 'feed_tag_links', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_tag_links_tag_id'), 'feed_tag_links', ['tag_id'], unique=False)
    op.create_index(op.f('ix_feed_tag_links_updated_at'), 'feed_tag_links', ['updated_at'], unique=False)
    op.create_table('group_messages',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_created_at'), 'group_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_messages_group_id'), 'group_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_messages_sender_id'), 'group_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_group_messages_updated_at'), 'group_messages', ['updated_at'], unique=False)
    op.create_table('group_participants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('background_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('regular', 'administrator', 'owner', name='group_member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_group_participants_created_at'), 'group_participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_participants_group_id'), 'group_participants', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_participants_updated_at'), 'group_participants', ['updated_at'], unique=False)
    op.create_index(op.f('ix_group_participants_user_id'), 'group_participants', ['user_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_created_at'), 'post_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_comments_updated_at'), 'post_comments', ['updated_at'], unique=False)
    op.create_table('post_engagements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('like', 'view', 'bookmark', name='post_engagement_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_engagement')
    )
    op.create_index(op.f('ix_post_engagements_created_at'), 'post_engagements', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_engagements_updated_at'), 'post_engagements', ['updated_at'], unique=False)
    op.create_table('post_tag_links',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag')
    )
    op.create_index(op.f('ix_post_tag_links_created_at'), 'post_tag_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_tag_links_post_id'), 'post_tag_links', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_tag_links_tag_id'), 'post_tag_links', ['tag_id'], unique=False)
    op.create_index(op.f('ix_post_tag_links_updated_at'), 'post_tag_links', ['updated_at'], unique=False)
    op.create_table('resume_skill_links',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('last_used_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='uq_resume_skill')
    )
    op.create_index(op.f('ix_resume_skill_links_created_at'), 'resume_skill_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_resume_skill_links_updated_at'), 'resume_skill_links', ['updated_at'], unique=False)
    op.create_table('saved_vacancies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_saved_vacancy')
    )
    op.create_index(op.f('ix_saved_vacancies_created_at'), 'saved_vacancies', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_vacancies_updated_at'), 'saved_vacancies', ['updated_at'], unique=False)
    op.create_table('vacancy_skill_links',
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('years_of_experience_min', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'skill_id', name='uq_vacancy_skill')
    )
    op.create_index(op.f('ix_vacancy_skill_links_created_at'), 'vacancy_skill_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_skill_links_updated_at'), 'vacancy_skill_links', ['updated_at'], unique=False)
    op.create_table('group_message_attachment_links',
    sa.Column('group_message_id', sa.UUID(), nullable=False),
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_message_id'], ['group_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_message_id', 'attachment_id', name='uq_group_message_attachment'),
    sa.UniqueConstraint('group_message_id', 'position', name='uq_group_message_attachment_position')
    )
    op.create_index(op.f('ix_group_message_attachment_links_attachment_id'), 'group_message_attachment_links', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_group_message_attachment_links_created_at'), 'group_message_attachment_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_message_attachment_links_group_message_id'), 'group_message_attachment_links', ['group_message_id'], unique=False)
    op.create_index(op.f('ix_group_message_attachment_links_updated_at'), 'group_message_attachment_links', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_message_attachment_links_updated_at'), table_name='group_message_attachment_links')
    op.drop_index(op.f('ix_group_message_attachment_links_group_message_id'), table_name='group_message_attachment_links')
    op.drop_index(op.f('ix_group_message_attachment_links_created_at'), table_name='group_message_attachment_links')
    op.drop_index(op.f('ix_group_message_attachment_links_attachment_id'), table_name='group_message_attachment_links')
    op.drop_table('group_message_attachment_links')
    op.drop_index(op.f('ix_vacancy_skill_links_updated_at'), table_name='vacancy_skill_links')
    op.drop_index(op.f('ix_vacancy_skill_links_created_at'), table_name='vacancy_skill_links')
    op.drop_table('vacancy_skill_links')
    op.drop_index(op.f('ix_saved_vacancies_updated_at'), table_name='saved_vacancies')
    op.drop_index(op.f('ix_saved_vacancies_created_at'), table_name='saved_vacancies')
    op.drop_table('saved_vacancies')
    op.drop_index(op.f('ix_resume_skill_links_updated_at'), table_name='resume_skill_links')
    op.drop_index(op.f('ix_resume_skill_links_created_at'), table_name='resume_skill_links')
    op.drop_table('resume_skill_links')
    op.drop_index(op.f('ix_post_tag_links_updated_at'), table_name='post_tag_links')
    op.drop_index(op.f('ix_post_tag_links_tag_id'), table_name='post_tag_links')
    op.drop_index(op.f('ix_post_tag_links_post_id'), table_name='post_tag_links')
    op.drop_index(op.f('ix_post_tag_links_created_at'), table_name='post_tag_links')
    op.drop_table('post_tag_links')
    op.drop_index(op.f('ix_post_engagements_updated_at'), table_name='post_engagements')
    op.drop_index(op.f('ix_post_engagements_created_at'), table_name='post_engagements')
    op.drop_table('post_engagements')
    op.drop_index(op.f('ix_post_comments_updated_at'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_created_at'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_group_participants_user_id'), table_name='group_participants')
    op.drop_index(op.f('ix_group_participants_updated_at'), table_name='group_participants')
    op.drop_index(op.f('ix_group_participants_group_id'), table_name='group_participants')
    op.drop_index(op.f('ix_group_participants_created_at'), table_name='group_participants')
    op.drop_table('group_participants')
    op.drop_index(op.f('ix_group_messages_updated_at'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_sender_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_group_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_created_at'), table_name='group_messages')
    op.drop_table('group_messages')
    op.drop_index(op.f('ix_feed_tag_links_updated_at'), table_name='feed_tag_links')
    op.drop_index(op.f('ix_feed_tag_links_tag_id'), table_name='feed_tag_links')
    op.drop_index(op.f('ix_feed_tag_links_feed_id'), table_name='feed_tag_links')
    op.drop_index(op.f('ix_feed_tag_links_created_at'), table_name='feed_tag_links')
    op.drop_table('feed_tag_links')
    op.drop_index(op.f('ix_feed_engagements_user_id'), table_name='feed_engagements')
    op.drop_index(op.f('ix_feed_engagements_updated_at'), table_name='feed_engagements')
    op.drop_index(op.f('ix_feed_engagements_feed_id'), table_name='feed_engagements')
    op.drop_index(op.f('ix_feed_engagements_created_at'), table_name='feed_engagements')
    op.drop_table('feed_engagements')
    op.drop_index(op.f('ix_feed_attachment_links_updated_at'), table_name='feed_attachment_links')
    op.drop_index(op.f('ix_feed_attachment_links_feed_id'), table_name='feed_attachment_links')
    op.drop_index(op.f('ix_feed_attachment_links_created_at'), table_name='feed_attachment_links')
    op.drop_index(op.f('ix_feed_attachment_links_attachment_id'), table_name='feed_attachment_links')
    op.drop_table('feed_attachment_links')
    op.drop_index(op.f('ix_chat_message_attachment_links_updated_at'), table_name='chat_message_attachment_links')
    op.drop_index(op.f('ix_chat_message_attachment_links_created_at'), table_name='chat_message_attachment_links')
    op.drop_index(op.f('ix_chat_message_attachment_links_chat_message_id'), table_name='chat_message_attachment_links')
    op.drop_index(op.f('ix_chat_message_attachment_links_attachment_id'), table_name='chat_message_attachment_links')
    op.drop_table('chat_message_attachment_links')
    op.drop_index(op.f('ix_applications_updated_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_work_experiences_updated_at'), table_name='work_experiences')
    op.drop_index(op.f('ix_work_experiences_created_at'), table_name='work_experiences')
    op.drop_table('work_experiences')
    op.drop_index(op.f('ix_vacancies_updated_at'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_title'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_specialization'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_created_at'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_country_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_city_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_user_skill_links_updated_at'), table_name='user_skill_links')
    op.drop_index(op.f('ix_user_skill_links_created_at'), table_name='user_skill_links')
    op.drop_table('user_skill_links')
    op.drop_index(op.f('ix_sessions_updated_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_resumes_updated_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_specialization'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_salary_expectation_min'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_salary_expectation_max'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_employment_type'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_country_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_city_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_posts_updated_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_oauth_users_updated_at'), table_name='oauth_users')
    op.drop_index(op.f('ix_oauth_users_created_at'), table_name='oauth_users')
    op.drop_table('oauth_users')
    op.drop_index(op.f('ix_groups_updated_at'), table_name='groups')
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_created_at'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_follows_updated_at'), table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_feeds_updated_at'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_quote_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_parent_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_created_at'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_category_id'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_author_id'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_company_members_updated_at'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_created_at'), table_name='company_members')
    op.drop_table('company_members')
    op.drop_index(op.f('ix_chat_participants_user_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_updated_at'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_last_seen_at'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_created_at'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_chat_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_chat_messages_updated_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_reply_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_attachments_updated_at'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_status'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_created_at'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_updated_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_date'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_country_id'), table_name='users')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_updated_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_created_at'), table_name='companies')
    op.drop_index(op.f('ix_companies_country_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_city_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_cities_updated_at'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_created_at'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_tags_updated_at'), table_name='tags')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_skills_updated_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_created_at'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_feed_categories_updated_at'), table_name='feed_categories')
    op.drop_index(op.f('ix_feed_categories_name'), table_name='feed_categories')
    op.drop_index(op.f('ix_feed_categories_created_at'), table_name='feed_categories')
    op.drop_table('feed_categories')
    op.drop_index(op.f('ix_countries_updated_at'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_created_at'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
