import base64
import hashlib
import os
import secrets
from urllib.parse import urlencode

import httpx
from fastapi import HTTPException, status
from pydantic import BaseModel

from src.utils.settings import get_settings

settings = get_settings()

"""
Field 	        Type 	    Description
sub 	        string 	    Required. An identifier for the user, unique among all Google Accounts and never reused. Case-sensitive string not exceeding 255 characters.
name 	        string 	    The user's full name, in a displayable form.
given_name 	    string 	    The user's given name(s) or first name(s).
family_name     string 	    The user's surname(s) or last name(s).
picture 	    string 	    The URL of the user's profile picture.
email 	        string 	    The user's email address.
email_verified 	boolean 	Whether the user's email address has been verified.
hd 	            string 	    The hosted domain associated with the user's Google Workspace or Cloud organization.
"""


class GoogleUserInfo(BaseModel):
    sub: str
    name: str | None = None
    given_name: str | None = None
    family_name: str | None = None
    picture: str | None = None
    email: str | None = None
    email_verified: bool = False


class GithubUserInfo(BaseModel):
    id: int
    login: str
    name: str | None = None
    email: str | None = None
    avatar_url: str


def build_pkce_pair() -> tuple[str, str]:
    """Returns (code_verifier, code_challenge)."""
    # Create a state token to prevent request forgery.
    # Store it in the session for later validation.
    _state = hashlib.sha256(os.urandom(1024)).hexdigest()

    verifier = secrets.token_urlsafe(32)
    digest = hashlib.sha256(verifier.encode()).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode()
    return verifier, challenge


# Authorization Endpoint https://developers.google.com/identity/openid-connect/reference#authorization_endpoint
def google_auth_url(code_challenge: str) -> str:
    params = {
        "client_id": settings.google_oauth.client_id,
        "redirect_uri": settings.google_oauth.redirect_url,
        "response_type": "code",
        "scope": "openid email profile",
        "state": "",  # should include the value of the anti-forgery unique session token, as well as any other information needed to recover the context when the user returns to your application, e.g., the starting URL
        "nonce": "",  # is a random value generated by your app that enables replay protection when present
        "code_challenge": code_challenge,
        "code_challenge_method": "S256",
        "access_type": "offline",
        "prompt": "consent",
    }
    return "https://accounts.google.com/o/oauth2/v2/auth?" + urlencode(params)


def github_auth_url(code_challenge: str) -> str:
    params = {
        "client_id": settings.github_oauth.client_id,
        "redirect_uri": settings.github_oauth.redirect_url,
        "scope": "user:email",
        "code_challenge": code_challenge,
        "code_challenge_method": "S256",
    }
    return "https://github.com/login/oauth/authorize?" + urlencode(params)


# Token Endpoint https://developers.google.com/identity/openid-connect/reference#token_endpoint
async def exchange_google_code(code: str, code_verifier: str) -> GoogleUserInfo:
    async with httpx.AsyncClient() as client:
        # Response body https://developers.google.com/identity/openid-connect/reference#response_body_2
        """
        {
            "access_token": string              // The Access Token that can be sent to a Google API.
            "expires_in": integer               // The lifetime of the Access Token in seconds, relative to the time the token was issued.
            "id_token": string                  // A JSON Web Token (JWT) that contains identity information about the user. This token is returned during the initial Authorization Code exchange and can also be returned during a Refresh Token request if the openid scope was granted.
            "scope": string                     // The scopes of access granted by the access_token expressed as a list of space-delimited, case-sensitive strings.
            "token_type": string                // The type of token returned. Always Bearer
            "refresh_token": string             // (Optional) A token that can be used to obtain new Access Tokens. This field is only returned in the initial exchange of an Authorization Code if access_type=offline was requested.
            "refresh_token_expires_in": integer //  	(Optional) The remaining lifetime of the Refresh Token in seconds. This value is only set when the user grants time-based access.
        }

        {
            "error": string             // An error code.
            "error_description": string // A description of the error if the request failed.
        }
        """

        res = await client.post(
            "https://oauth2.googleapis.com/token",
            params={
                "code": code,
                "client_id": settings.google_oauth.client_id,
                "client_secret": settings.google_oauth.client_secret,
                "redirect_uri": settings.google_oauth.redirect_url,
                "grant_type": "authorization_code",
                "code_verifier": code_verifier,
            },
        )
        if not res.is_success:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "Google token exchange failed")

        data: dict = res.json()
        access_token: str = data.get("access_token", "")

        # UserInfo Endpoint https://developers.google.com/identity/openid-connect/reference#userinfo_endpoint
        user_res = await client.get(
            "https://openidconnect.googleapis.com/v1/userinfo",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        if not user_res.is_success:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "Failed to fetch Google user")

        return GoogleUserInfo.model_validate(user_res.json())


async def exchange_github_code(code: str, code_verifier: str) -> GithubUserInfo:
    async with httpx.AsyncClient() as client:
        token_res = await client.post(
            "https://github.com/login/oauth/access_token",
            headers={"Accept": "application/json"},
            data={
                "code": code,
                "client_id": settings.github_oauth.client_id,
                "client_secret": settings.github_oauth.client_secret,
                "redirect_uri": settings.github_oauth.redirect_url,
                "code_verifier": code_verifier,
            },
        )
        if not token_res.is_success:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "GitHub token exchange failed")

        access_token: str = token_res.json()["access_token"]

        user_res = await client.get(
            "https://api.github.com/user",
            headers={"Authorization": f"Bearer {access_token}", "User-Agent": "YourApp"},
        )
        if not user_res.is_success:
            raise HTTPException(status.HTTP_400_BAD_REQUEST, "Failed to fetch GitHub user")

        return GithubUserInfo.model_validate(user_res.json())
